language: perl

perl:
- '5.26'

sudo: false

before_install:
- git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-test.git
- chmod +x travisci/harness.sh
install:
- cpanm -v --installdeps --notest .

script: ./travisci/harness.sh
notifications:
  email:
    recipients:
       - zdfimpbw@tafmail.com
    on_success: always
    on_failure: always
